import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

const moodScale = [
  { value: 1, emoji: '😭', labelKey: 'mood.terrible', fallback: 'Terrible' },
  { value: 2, emoji: '😢', labelKey: 'mood.veryBad', fallback: 'Very Bad' },
  { value: 3, emoji: '😔', labelKey: 'mood.bad', fallback: 'Bad' },
  { value: 4, emoji: '😕', labelKey: 'mood.poor', fallback: 'Poor' },
  { value: 5, emoji: '😐', labelKey: 'mood.neutral', fallback: 'Neutral' },
  { value: 6, emoji: '🙂', labelKey: 'mood.okay', fallback: 'Okay' },
  { value: 7, emoji: '😊', labelKey: 'mood.good', fallback: 'Good' },
  { value: 8, emoji: '😄', labelKey: 'mood.veryGood', fallback: 'Very Good' },
  { value: 9, emoji: '😁', labelKey: 'mood.great', fallback: 'Great' },
  { value: 10, emoji: '🤩', labelKey: 'mood.amazing', fallback: 'Amazing' },
];

const MoodHistory = ({ moodHistory, isLoading }) => {
  const { t } = useTranslation();
  const entries = Array.isArray(moodHistory) ? moodHistory : [];

  const moodByValue = useMemo(() => {
    return Object.fromEntries(moodScale.map((m) => [m.value, m]));
  }, []);

  if (isLoading) {
    return (
      <div className="card history-card">
        <div className="card-header">
          <h3 className="card-title">{t('mood.recentMoods', 'Recent Moods')}</h3>
        </div>
        <div className="mood-history">
          <div className="loading-state">{t('mood.loadingHistory', 'Loading mood history...')}</div>
        </div>
      </div>
    );
  }

  if (entries.length === 0) {
    return (
      <div className="empty-state">
        <div className="empty-icon">
          <svg width="64" height="64" viewBox="0 0 64 64" fill="none">
            <circle cx="32" cy="32" r="28" fill="var(--primary-green)" opacity="0.1" />
            <path
              d="M20 32c0-6.6 5.4-12 12-12s12 5.4 12 12-5.4 12-12 12-12-5.4-12-12z"
              fill="var(--primary-green)"
              opacity="0.3"
            />
            <path
              d="M26 28h4M34 28h4M24 38s4 4 8 4 8-4 8-4"
              stroke="var(--primary-green)"
              strokeWidth="2"
              fill="none"
            />
          </svg>
        </div>
        <h3 className="empty-title">{t('mood.emptyTitle', 'No mood entries yet')}</h3>
        <p className="empty-description">
          {t(
            'mood.emptyDescription',
            'Start tracking your mood to see insights and trends over time.'
          )}
        </p>
      </div>
    );
  }

  return (
    <div className="card history-card">
      <div className="card-header">
        <h3 className="card-title">{t('mood.recentMoods', 'Recent Moods')}</h3>
      </div>
      <div className="mood-history">
        {entries.slice(0, 10).map((entry) => {
          const mood = moodByValue[entry.moodValue];
          const isAutoGenerated = Boolean(entry.isAutoGenerated);

          return (
            <div
              key={entry.id}
              className={`history-item ${isAutoGenerated ? 'auto-generated' : ''}`}
            >
              <div className="history-mood">
                <span className="history-emoji">{mood?.emoji || '😐'}</span>
                <div className="history-details">
                  <span className="history-label">
                    {mood ? t(mood.labelKey, mood.fallback) : t('mood.unknown', 'Unknown')} (
                    {entry.moodValue}/10)
                  </span>
                  {entry.notes && <span className="history-notes">{entry.notes}</span>}
                  {isAutoGenerated && <span className="auto-badge">Auto-generated</span>}
                </div>
              </div>
              <div className="history-time">
                {new Date(entry.createdAt).toLocaleDateString([], {
                  weekday: 'short',
                  month: 'short',
                  day: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default MoodHistory;
